name: Automation Go

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Preparing
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.x'
      - name: Linting
        run: |
          /bin/sh .github/workflows/golang.linter.sh
      - name: Testing
        run: |
          /bin/sh .github/workflows/golang.tester.sh
      - name: Reporting
        uses: codecov/codecov-action@v1
        with:
          flags: golang
